<a href="https://colab.research.google.com/github/FawneeCakes/pandas-challenge/blob/main/PyCitySchools_starter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
# Find the latest version of spark 3.x  from https://downloads.apache.org/spark/ and enter as the spark version
# For example:
# spark_version = 'spark-3.5.1'
spark_version = 'spark-3.5.1'
os.environ['SPARK_VERSION']=spark_version

# Install Spark and Java
!apt-get update
!apt-get install openjdk-11-jdk-headless -qq > /dev/null
!wget -q https://downloads.apache.org/spark/$SPARK_VERSION/$SPARK_VERSION-bin-hadoop3.tgz
!tar xf $SPARK_VERSION-bin-hadoop3.tgz
!pip install -q findspark

# Set Environment Variables
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"] = f"/content/{spark_version}-bin-hadoop3"

# Start a SparkSession
import findspark
findspark.init()

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Get:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:7 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:11 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [929 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,093 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1,922 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [2,474 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [2,552 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [51.8 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2,187 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,392 kB]
Fetched 12.9 MB in 6s (1,997 kB/s)
Reading package lists... Done

In [3]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to Change These)
school_data_to_load = "Resources/schools_complete.csv"
student_data_to_load = "Resources/students_complete.csv"

# Read School and Student Data File and store into Pandas DataFrames
school_data = pd.read_csv(school_data_to_load)
student_data = pd.read_csv(student_data_to_load)


# Combine the data into a single dataset.
school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])
school_data_complete.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635

**District Summary**

In [4]:
school_data.head()

   School ID            school_name      type  size   budget
0          0      Huang High School  District  2917  1910635
1          1   Figueroa High School  District  2949  1884411
2          2    Shelton High School   Charter  1761  1056600
3          3  Hernandez High School  District  4635  3022020
4          4    Griffin High School   Charter  1468   917500

In [5]:
student_data.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84

In [6]:
# Calculate the total number of unique schools
school_count = len(school_data["school_name"].unique())
school_count

15

In [7]:
# Calculate the total number of students
student_count = school_data_complete.student_name.count()
student_count

39170

In [8]:
# Calculate the total budget
total_budget = school_data["budget"].sum()
total_budget

24649428

In [9]:
# Calculate the average (mean) math score
average_math_score = school_data_complete["math_score"].mean()
average_math_score

78.98537145774827

In [10]:
# Calculate the average (mean) reading score
average_reading_score = school_data_complete["reading_score"].mean()
average_reading_score

81.87784018381414

In [11]:
school_data_complete.dtypes

Student ID        int64
student_name     object
gender           object
grade            object
school_name      object
reading_score     int64
math_score        int64
School ID         int64
type             object
size              int64
budget            int64
dtype: object

In [12]:
# Use the following to calculate the percentage of students who passed math (math scores greather than or equal to 70)
passing_math_count = school_data_complete[(school_data_complete["math_score"] >= 70)].count()["student_name"]
passing_math_percentage = passing_math_count / student_count * 100
passing_math_percentage

74.9808526933878

In [13]:
# Calculate the percentage of students who passeed reading (hint: look at how the math percentage was calculated)
passing_reading_count = school_data_complete[(school_data_complete["reading_score"] >= 70)].count()["student_name"]
passing_reading_percentage = passing_reading_count / student_count * 100
passing_reading_percentage

85.80546336482001

In [14]:
# Use the following to calculate the percentage of students that passed math and reading
passing_math_reading_count = school_data_complete[
    (school_data_complete["math_score"] >= 70) & (school_data_complete["reading_score"] >= 70)
].count()["student_name"]
overall_passing_rate = passing_math_reading_count /  float(student_count) * 100
overall_passing_rate

65.17232575950983

In [15]:
# Create a high-level snapshot of the district's key metrics in a DataFrame
district_summary = pd.DataFrame({"Total Schools":[school_count], "Total Students":[student_count],"Total Budget":[total_budget],
                                "Average Math Score":[average_math_score], "Average Reading Score":[average_reading_score],
                                "% Passing Math":[passing_math_percentage],"% Passing Reading":[passing_reading_percentage],
                                "% Overall Passing":[overall_passing_rate]})


# Formatting
district_summary["Total Students"] = district_summary["Total Students"].map("{:,}".format)
district_summary["Total Budget"] = district_summary["Total Budget"].map("${:,.2f}".format)
district_summary["Average Math Score"] = district_summary["Average Math Score"].map("{:.1f}".format)
district_summary["Average Reading Score"] = district_summary["Average Reading Score"].map("{:.1f}".format)
district_summary["% Passing Math"] = district_summary["% Passing Math"].map("{:.1f}".format)
district_summary["% Passing Reading"] = district_summary["% Passing Reading"].map("{:.1f}".format)
district_summary["% Overall Passing"] = district_summary["% Overall Passing"].map("{:.1f}".format)

# Display the DataFrame
district_summary

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
0,15,"39,170","$24,649,428.00",79.0,81.9,75.0,85.8,65.2

**School Summary**

In [16]:
# Use the code provided to select the school type
school_types = school_data.set_index(["school_name"])["type"]
school_types

school_name
Huang High School        District
Figueroa High School     District
Shelton High School       Charter
Hernandez High School    District
Griffin High School       Charter
Wilson High School        Charter
Cabrera High School       Charter
Bailey High School       District
Holden High School        Charter
Pena High School          Charter
Wright High School        Charter
Rodriguez High School    District
Johnson High School      District
Ford High School         District
Thomas High School        Charter
Name: type, dtype: object

In [17]:
# Calculate the total student count
per_school_counts = school_data_complete["school_name"].value_counts()
per_school_counts

school_name
Bailey High School       4976
Johnson High School      4761
Hernandez High School    4635
Rodriguez High School    3999
Figueroa High School     2949
Huang High School        2917
Ford High School         2739
Wilson High School       2283
Cabrera High School      1858
Wright High School       1800
Shelton High School      1761
Thomas High School       1635
Griffin High School      1468
Pena High School          962
Holden High School        427
Name: count, dtype: int64

In [19]:
# Calculate the total school budget and per capita spending
per_school_budget = school_data_complete.groupby(["school_name"])["budget"].mean() # removed .mean() after groupby and added it after ["budget"] to only calculate the mean of the budget column
per_school_capita = per_school_budget / per_school_counts

print(per_school_budget ,'\n')
print(per_school_capita)

school_name
Bailey High School       3124928.0
Cabrera High School      1081356.0
Figueroa High School     1884411.0
Ford High School         1763916.0
Griffin High School       917500.0
Hernandez High School    3022020.0
Holden High School        248087.0
Huang High School        1910635.0
Johnson High School      3094650.0
Pena High School          585858.0
Rodriguez High School    2547363.0
Shelton High School      1056600.0
Thomas High School       1043130.0
Wilson High School       1319574.0
Wright High School       1049400.0
Name: budget, dtype: float64

school_name
Bailey High School       628.0
Cabrera High School      582.0
Figueroa High School     639.0
Ford High School         644.0
Griffin High School      625.0
Hernandez High School    652.0
Holden High School       581.0
Huang High School        655.0
Johnson High School      650.0
Pena High School         609.0
Rodriguez High School    637.0
Shelton High School      600.0
Thomas High School       638.0
Wilson High School       578.0
Wright High School       583.0
dtype: float64

In [20]:
# Calculate the average test scores
per_school_math = school_data_complete.groupby(["school_name"])["math_score"].mean()
per_school_reading = school_data_complete.groupby(["school_name"])["reading_score"].mean()

print(per_school_math,'\n')
print(per_school_reading)

school_name
Bailey High School       77.048432
Cabrera High School      83.061895
Figueroa High School     76.711767
Ford High School         77.102592
Griffin High School      83.351499
Hernandez High School    77.289752
Holden High School       83.803279
Huang High School        76.629414
Johnson High School      77.072464
Pena High School         83.839917
Rodriguez High School    76.842711
Shelton High School      83.359455
Thomas High School       83.418349
Wilson High School       83.274201
Wright High School       83.682222
Name: math_score, dtype: float64

school_name
Bailey High School       81.033963
Cabrera High School      83.975780
Figueroa High School     81.158020
Ford High School         80.746258
Griffin High School      83.816757
Hernandez High School    80.934412
Holden High School       83.814988
Huang High School        81.182722
Johnson High School      80.966394
Pena High School         84.044699
Rodriguez High School    80.744686
Shelton High School      83.725724
Thomas High School       83.848930
Wilson High School       83.989488
Wright High School       83.955000
Name: reading_score, dtype: float64

In [21]:
# Calculate the number of schools with math scores of 70 or higher
school_passing_math = school_data_complete[school_data_complete["math_score"] >= 70].groupby("school_name")["math_score"].count() / per_school_counts * 100
num_schools_passing_math = (school_passing_math >= 70).sum()

print(school_passing_math,'\n')
print ("Number of schools with math scores of 70 or higher: ", num_schools_passing_math)

school_name
Bailey High School       66.680064
Cabrera High School      94.133477
Figueroa High School     65.988471
Ford High School         68.309602
Griffin High School      93.392371
Hernandez High School    66.752967
Holden High School       92.505855
Huang High School        65.683922
Johnson High School      66.057551
Pena High School         94.594595
Rodriguez High School    66.366592
Shelton High School      93.867121
Thomas High School       93.272171
Wilson High School       93.867718
Wright High School       93.333333
dtype: float64

Number of schools with math scores of 70 or higher:  8

In [22]:
# Calculate the number of schools with reading scores of 70 or higher
school_passing_reading = chool_passing_math = school_data_complete[school_data_complete["reading_score"] >= 70].groupby("school_name")["reading_score"].count() / per_school_counts * 100
num_schools_passing_reading = (school_passing_reading >= 70).sum()

print(school_passing_reading,'\n')
print ("Number of schools with reading scores of 70 or higher: ", num_schools_passing_reading)

school_name
Bailey High School       81.933280
Cabrera High School      97.039828
Figueroa High School     80.739234
Ford High School         79.299014
Griffin High School      97.138965
Hernandez High School    80.862999
Holden High School       96.252927
Huang High School        81.316421
Johnson High School      81.222432
Pena High School         95.945946
Rodriguez High School    80.220055
Shelton High School      95.854628
Thomas High School       97.308869
Wilson High School       96.539641
Wright High School       96.611111
dtype: float64

Number of schools with reading scores of 70 or higher:  15

In [23]:
# Use the provided code to calculate the schools that passed both math and reading with scores of 70 or higher
school_passing_math = school_data_complete[school_data_complete["math_score"] >= 70].groupby("school_name")["math_score"].count() / per_school_counts * 100
school_passing_reading = school_data_complete[school_data_complete["reading_score"] >= 70].groupby("school_name")["reading_score"].count() / per_school_counts * 100
passing_math_and_reading_TF = (school_passing_math >= 70) & (school_passing_reading >= 70).sum()
passing_math_and_reading = passing_math_and_reading_TF.sum()

print(passing_math_and_reading_TF,'\n')
print("Number of schools with math and reading scores of 70 or higher: ",passing_math_and_reading)

school_name
Bailey High School       False
Cabrera High School       True
Figueroa High School     False
Ford High School         False
Griffin High School       True
Hernandez High School    False
Holden High School        True
Huang High School        False
Johnson High School      False
Pena High School          True
Rodriguez High School    False
Shelton High School       True
Thomas High School        True
Wilson High School        True
Wright High School        True
dtype: bool

Number of schools with math and reading scores of 70 or higher:  8

In [24]:
# Use the provided code to calculate the passing rates
# Calculate the percentage of students who passed math per school
school_passing_math = school_data_complete[school_data_complete["math_score"] >= 70].groupby("school_name")["math_score"].count()
per_school_passing_math = school_passing_math / per_school_counts * 100

# Calculate the percentage of students who passed reading per school
school_passing_reading = school_data_complete[school_data_complete["reading_score"] >= 70].groupby("school_name")["reading_score"].count()
per_school_passing_reading = school_passing_reading / per_school_counts * 100

# Calculate the percentage of students who passed both math and reading per school
school_passing_math_and_reading = school_data_complete[(school_data_complete["math_score"] >= 70) & (school_data_complete["reading_score"] >= 70)].groupby("school_name")["student_name"].count()
per_school_passing_math_and_reading = school_passing_math_and_reading / per_school_counts * 100

# Print the passing rates per school
print("Passing math percentage per school:\n", per_school_passing_math)
print("\nPassing reading percentage per school:\n", per_school_passing_reading)
print("\nOverall passing percentage per school:\n", per_school_passing_math_and_reading)

Passing math percentage per school:
 school_name
Bailey High School       66.680064
Cabrera High School      94.133477
Figueroa High School     65.988471
Ford High School         68.309602
Griffin High School      93.392371
Hernandez High School    66.752967
Holden High School       92.505855
Huang High School        65.683922
Johnson High School      66.057551
Pena High School         94.594595
Rodriguez High School    66.366592
Shelton High School      93.867121
Thomas High School       93.272171
Wilson High School       93.867718
Wright High School       93.333333
dtype: float64

Passing reading percentage per school:
 school_name
Bailey High School       81.933280
Cabrera High School      97.039828
Figueroa High School     80.739234
Ford High School         79.299014
Griffin High School      97.138965
Hernandez High School    80.862999
Holden High School       96.252927
Huang High School        81.316421
Johnson High School      81.222432
Pena High School         95.945946
Rodriguez High School    80.220055
Shelton High School      95.854628
Thomas High School       97.308869
Wilson High School       96.539641
Wright High School       96.611111
dtype: float64

Overall passing percentage per school:
 school_name
Bailey High School       54.642283
Cabrera High School      91.334769
Figueroa High School     53.204476
Ford High School         54.289887
Griffin High School      90.599455
Hernandez High School    53.527508
Holden High School       89.227166
Huang High School        53.513884
Johnson High School      53.539172
Pena High School         90.540541
Rodriguez High School    52.988247
Shelton High School      89.892107
Thomas High School       90.948012
Wilson High School       90.582567
Wright High School       90.333333
dtype: float64

In [25]:
# Create a DataFrame called `per_school_summary` with columns for the calculations above.
per_school_summary = pd.DataFrame({"School Type":school_types, "Total Students":per_school_counts, "Total School Budget":per_school_budget
                                ,"Per Student Budget":per_school_capita ,"Average Math Score":per_school_math,
                                "Average Reading Score":school_passing_reading,
                                "% Passing Math":per_school_passing_math, "% Passing Reading":per_school_passing_reading,
                                "% Overall Passing":per_school_passing_math_and_reading})

# Formatting
per_school_summary["Total School Budget"] = per_school_summary["Total School Budget"].map("${:,.2f}".format)
per_school_summary["Per Student Budget"] = per_school_summary["Per Student Budget"].map("${:,.2f}".format)
per_school_summary["Average Math Score"] = per_school_summary["Average Math Score"].map("{:.3f}".format)
per_school_summary["Average Reading Score"] = per_school_summary["Average Reading Score"].map("{:.3f}".format)
per_school_summary["% Passing Math"] = per_school_summary["% Passing Math"].map("{:.3f}".format)
per_school_summary["% Passing Reading"] = per_school_summary["% Passing Reading"].map("{:.3f}".format)
per_school_summary["% Overall Passing"] = per_school_summary["% Overall Passing"].map("{:.3f}".format)

# Display the DataFrame
per_school_summary

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
school_name,,,,,,,,,
Bailey High School,District,4976,"$3,124,928.00",$628.00,77.048,4077.000,66.680,81.933,54.642
Cabrera High School,Charter,1858,"$1,081,356.00",$582.00,83.062,1803.000,94.133,97.040,91.335
Figueroa High School,District,2949,"$1,884,411.00",$639.00,76.712,2381.000,65.988,80.739,53.204
Ford High School,District,2739,"$1,763,916.00",$644.00,77.103,2172.000,68.310,79.299,54.290
Griffin High School,Charter,1468,"$917,500.00",$625.00,83.351,1426.000,93.392,97.139,90.599
Hernandez High School,District,4635,"$3,022,020.00",$652.00,77.290,3748.000,66.753,80.863,53.528
Holden High School,Charter,427,"$248,087.00",$581.00,83.803,411.000,92.506,96.253,89.227
Huang High School,District,2917,"$1,910,635.00",$655.00,76.629,2372.000,65.684,81.316,53.514
Johnson High School,District,4761,"$3,094,650.00",$650.00,77.072,3867.000,66.058,81.222,53.539
Pena High School,Charter,962,"$585,858.00",$609.00,83.840,923.000,94.595,95.946,90.541
Rodriguez High School,District,3999,"$2,547,363.00",$637.00,76.843,3208.000,66.367,80.220,52.988
Shelton High School,Charter,1761,"$1,056,600.00",$600.00,83.359,1688.000,93.867,95.855,89.892
Thomas High School,Charter,1635,"$1,043,130.00",$638.00,83.418,1591.000,93.272,97.309,90.948
Wilson High School,Charter,2283,"$1,319,574.00",$578.00,83.274,2204.000,93.868,96.540,90.583
Wright High School,Charter,1800,"$1,049,400.00",$583.00,83.682,1739.000,93.333,96.611,90.333

**Highest-Performing Schools (by % Overall Passing)**

In [26]:
# Sort the schools by `% Overall Passing` in descending order and display the top 5 rows.
top_school = per_school_summary.sort_values(["% Overall Passing"], ascending=False)
top_school.head()

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
school_name,,,,,,,,,
Cabrera High School,Charter,1858,"$1,081,356.00",$582.00,83.062,1803.000,94.133,97.040,91.335
Thomas High School,Charter,1635,"$1,043,130.00",$638.00,83.418,1591.000,93.272,97.309,90.948
Griffin High School,Charter,1468,"$917,500.00",$625.00,83.351,1426.000,93.392,97.139,90.599
Wilson High School,Charter,2283,"$1,319,574.00",$578.00,83.274,2204.000,93.868,96.540,90.583
Pena High School,Charter,962,"$585,858.00",$609.00,83.840,923.000,94.595,95.946,90.541

**Bottom Performing Schools (By % Overall Passing)**

In [27]:
# Sort the schools by `% Overall Passing` in ascending order and display the top 5 rows.
bottom_school = per_school_summary.sort_values(["% Overall Passing"], ascending=True)
bottom_school.head()

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
school_name,,,,,,,,,
Rodriguez High School,District,3999,"$2,547,363.00",$637.00,76.843,3208.000,66.367,80.220,52.988
Figueroa High School,District,2949,"$1,884,411.00",$639.00,76.712,2381.000,65.988,80.739,53.204
Huang High School,District,2917,"$1,910,635.00",$655.00,76.629,2372.000,65.684,81.316,53.514
Hernandez High School,District,4635,"$3,022,020.00",$652.00,77.290,3748.000,66.753,80.863,53.528
Johnson High School,District,4761,"$3,094,650.00",$650.00,77.072,3867.000,66.058,81.222,53.539

**Math Scores by Grade**

In [29]:
# Use the code provided to separate the data by grade
ninth_graders = school_data_complete[(school_data_complete["grade"] == "9th")]
tenth_graders = school_data_complete[(school_data_complete["grade"] == "10th")]
eleventh_graders = school_data_complete[(school_data_complete["grade"] == "11th")]
twelfth_graders = school_data_complete[(school_data_complete["grade"] == "12th")]

# Group by "school_name" and take the mean of each.
ninth_graders_scores = ninth_graders.groupby(["school_name"]).mean(numeric_only=True) # Specify numeric_only to calculate mean for numeric columns
tenth_graders_scores = tenth_graders.groupby(["school_name"]).mean(numeric_only=True)
eleventh_graders_scores = eleventh_graders.groupby(["school_name"]).mean(numeric_only=True)
twelfth_graders_scores = twelfth_graders.groupby(["school_name"]).mean(numeric_only=True)

# Use the code to select only the `math_score`.
ninth_grade_math_scores = ninth_graders_scores["math_score"]
tenth_grade_math_scores = tenth_graders_scores["math_score"]
eleventh_grade_math_scores = eleventh_graders_scores["math_score"]
twelfth_grade_math_scores = twelfth_graders_scores["math_score"]

# Combine each of the scores above into single DataFrame called `math_scores_by_grade`
math_scores_by_grade = pd.DataFrame({'9th':ninth_grade_math_scores,'10th':tenth_grade_math_scores,'11th':eleventh_grade_math_scores,'12th':twelfth_grade_math_scores})

# Minor data wrangling
math_scores_by_grade.index.name = None

# Display the DataFrame
math_scores_by_grade

                             9th       10th       11th       12th
Bailey High School     77.083676  76.996772  77.515588  76.492218
Cabrera High School    83.094697  83.154506  82.765560  83.277487
Figueroa High School   76.403037  76.539974  76.884344  77.151369
Ford High School       77.361345  77.672316  76.918058  76.179963
Griffin High School    82.044010  84.229064  83.842105  83.356164
Hernandez High School  77.438495  77.337408  77.136029  77.186567
Holden High School     83.787402  83.429825  85.000000  82.855422
Huang High School      77.027251  75.908735  76.446602  77.225641
Johnson High School    77.187857  76.691117  77.491653  76.863248
Pena High School       83.625455  83.372000  84.328125  84.121547
Rodriguez High School  76.859966  76.612500  76.395626  77.690748
Shelton High School    83.420755  82.917411  83.383495  83.778976
Thomas High School     83.590022  83.087886  83.498795  83.497041
Wilson High School     83.085578  83.724422  83.195326  83.035794
Wright High School     83.264706  84.010288  83.836782  83.644986

**Reading Score by Grade**

In [31]:
# Use the code provided to separate the data by grade
ninth_graders = school_data_complete[(school_data_complete["grade"] == "9th")]
tenth_graders = school_data_complete[(school_data_complete["grade"] == "10th")]
eleventh_graders = school_data_complete[(school_data_complete["grade"] == "11th")]
twelfth_graders = school_data_complete[(school_data_complete["grade"] == "12th")]

# Group by "school_name" and take the mean of each.
ninth_graders_scores = ninth_graders.groupby(["school_name"]).mean(numeric_only=True) # Calculate mean for numeric columns only
tenth_graders_scores = tenth_graders.groupby(["school_name"]).mean(numeric_only=True)
eleventh_graders_scores = eleventh_graders.groupby(["school_name"]).mean(numeric_only=True)
twelfth_graders_scores = twelfth_graders.groupby(["school_name"]).mean(numeric_only=True)

# Use the code to select only the `reading_score`.
ninth_grade_reading_scores = ninth_graders_scores["reading_score"]
tenth_grader_reading_scores = tenth_graders_scores["reading_score"]
eleventh_grader_reading_scores = eleventh_graders_scores["reading_score"]
twelfth_grader_reading_scores = twelfth_graders_scores["reading_score"]

# Combine each of the scores above into single DataFrame called `reading_scores_by_grade`
reading_scores_by_grade = pd.DataFrame({'9th':ninth_grade_math_scores,'10th':tenth_grade_math_scores,'11th':eleventh_grade_math_scores,'12th':twelfth_grade_math_scores})

# Minor data wrangling
reading_scores_by_grade = reading_scores_by_grade[["9th", "10th", "11th", "12th"]]
reading_scores_by_grade.index.name = None

# Display the DataFrame
reading_scores_by_grade

                             9th       10th       11th       12th
Bailey High School     77.083676  76.996772  77.515588  76.492218
Cabrera High School    83.094697  83.154506  82.765560  83.277487
Figueroa High School   76.403037  76.539974  76.884344  77.151369
Ford High School       77.361345  77.672316  76.918058  76.179963
Griffin High School    82.044010  84.229064  83.842105  83.356164
Hernandez High School  77.438495  77.337408  77.136029  77.186567
Holden High School     83.787402  83.429825  85.000000  82.855422
Huang High School      77.027251  75.908735  76.446602  77.225641
Johnson High School    77.187857  76.691117  77.491653  76.863248
Pena High School       83.625455  83.372000  84.328125  84.121547
Rodriguez High School  76.859966  76.612500  76.395626  77.690748
Shelton High School    83.420755  82.917411  83.383495  83.778976
Thomas High School     83.590022  83.087886  83.498795  83.497041
Wilson High School     83.085578  83.724422  83.195326  83.035794
Wright High School     83.264706  84.010288  83.836782  83.644986

**Scores by School Spending**

In [32]:
# Establish the bins
spending_bins = [0, 585, 630, 645, 680]
ranges = ["<$585", "$585-630", "$630-645", "$645-680"]

In [33]:
# Create a copy of the school summary since it has the "Per Student Budget"
school_spending_df = per_school_summary.copy()

In [56]:
# Create a column with the spending range for each school
school_spending_df["Spending Ranges (Per Student)"] = pd.cut(school_spending_df["Per Student Budget"], spending_bins, labels=ranges)

school_spending_df

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing,Spending Ranges (Per Student)
school_name,,,,,,,,,,
Bailey High School,District,4976,"$3,124,928.00",NaN,77.048,4077.000,66.680,81.933,54.642,NaN
Cabrera High School,Charter,1858,"$1,081,356.00",NaN,83.062,1803.000,94.133,97.040,91.335,NaN
Figueroa High School,District,2949,"$1,884,411.00",NaN,76.712,2381.000,65.988,80.739,53.204,NaN
Ford High School,District,2739,"$1,763,916.00",NaN,77.103,2172.000,68.310,79.299,54.290,NaN
Griffin High School,Charter,1468,"$917,500.00",NaN,83.351,1426.000,93.392,97.139,90.599,NaN
Hernandez High School,District,4635,"$3,022,020.00",NaN,77.290,3748.000,66.753,80.863,53.528,NaN
Holden High School,Charter,427,"$248,087.00",NaN,83.803,411.000,92.506,96.253,89.227,NaN
Huang High School,District,2917,"$1,910,635.00",NaN,76.629,2372.000,65.684,81.316,53.514,NaN
Johnson High School,District,4761,"$3,094,650.00",NaN,77.072,3867.000,66.058,81.222,53.539,NaN
Pena High School,Charter,962,"$585,858.00",NaN,83.840,923.000,94.595,95.946,90.541,NaN
Rodriguez High School,District,3999,"$2,547,363.00",NaN,76.843,3208.000,66.367,80.220,52.988,NaN
Shelton High School,Charter,1761,"$1,056,600.00",NaN,83.359,1688.000,93.867,95.855,89.892,NaN
Thomas High School,Charter,1635,"$1,043,130.00",NaN,83.418,1591.000,93.272,97.309,90.948,NaN
Wilson High School,Charter,2283,"$1,319,574.00",NaN,83.274,2204.000,93.868,96.540,90.583,NaN
Wright High School,Charter,1800,"$1,049,400.00",NaN,83.682,1739.000,93.333,96.611,90.333,NaN

**Scores by School Size**